parameters:
    MesalabAdminBundle:
        AdminUser:
            namespace: MesalabAdminBundle
            class_name: AdminUser
            routing_prefix: admin_adminuser
            pager:
                perpage: 10
            sort:
                field: position
                order: ASC